# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BadStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for BadStore
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire', '~> 5.1'
  pod 'NMapsMap'
  pod 'RxSwift'
  pod 'RxCocoa'
end
